name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Keystore
        run: |
            # 生成一个新的 keystore 文件
            keytool -genkey -v -keystore keystore.jks -keyalg RSA -keysize 2048 \
                -validity 10000 -alias my-key-alias \
                -dname "CN=My Name, OU=My Org Unit, O=My Org, L=My City, ST=My State, C=My Country" \
                -storepass myKeystorePass -keypass myKeyPass

      - name: Build unsigned APK
        run: |
          keytool -list -v -keystore keystore.jks -storepass myKeystorePass
          ./gradlew assembleRelease
          ls -l app/build/outputs/apk/release

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
              -keystore keystore.jks -storepass myKeystorePass \
              -keypass myKeyPass \
              app/build/outputs/apk/release/app-release-unsigned.apk my-key-alias
          
          # 验证签名
          jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release-unsigned.apk
          
          # 使用 zipalign 进行优化
          ${ANDROID_HOME}/build-tools/$(ls ${ANDROID_HOME}/build-tools | tail -n 1)/zipalign -v 4 \
              app/build/outputs/apk/release/app-release-unsigned.apk \
              app/build/outputs/apk/release/app-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
