name: Android Build & Release

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: gradle

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Generate Android App Icon
              uses: masaeedu/android-icon-generator@v4
              with:
                  icon-file: 'pakeplus.png' # 你的图标文件路径
                  output-directory: 'app/src/main/res' # 输出到Android资源目录

            - name: Grant Execute Permission for Gradle
              run: chmod +x ./gradlew

            - name: Build Debug APK (可安装版本)
              run: ./gradlew assembleDebug

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: app/build/outputs/apk/debug/*.apk
                  tag_name: 'PakePlus-v0.0.1'
                  body: 'PakePlus-v0.0.1'
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
