name: Android Build & Release

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Grant Execute Permission for Gradle
              run: chmod +x ./gradlew

            - name: Build Release APK
              run: ./gradlew assembleRelease

            - name: Find APK File
              id: find_apk
              run: echo "::set-output name=apk_path::$(find app/build/outputs/apk/release -name '*.apk' | head -n 1)"

            - name: Upload APK as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: ${{ steps.find_apk.outputs.apk_path }}

    release:
        name: Release APK
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Download APK Artifact
              uses: actions/download-artifact@v4
              with:
                  name: release-apk
                  path: ./

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: '*.apk'
                  tag_name: 'PakePlus-v0.0.1'
                  release_name: 'PakePlus-v0.0.1'
                  body: 'PakePlus-v0.0.1'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
